version: "3.8"

# include:
#   - cinema_db/cinema_db.yml
networks:
  cinema_service_network:
    name: "cinema_service_net"
    driver: bridge
  cinema_db_network:
    name: "cinema_db_network"
    external: true

services:
  cinema_service:
    build: ./
    command: ./bin/app
    volumes:
      - ./docker/containers-configs/:/configs
    ports:
      - 9080:8080
    networks:
      - cinema_service_network
      - cinema_db_network
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    # depends_on:
    #   cinema_pool:
    #     condition: service_started
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "admin_cinema_service"
      org.label-schema.group: "monitoring"
